In [1]:
import librosa
import librosa.display
import soundfile as sf
import sounddevice as sd
import os
import numpy as np
import pandas as pd
import random
import random
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [5]:
#play the audio you recorded
DATADIR = 'C:\\Users\\UPES\\Pictures\\Audio_Speech_analysis\\codes\\pd_data_for_emotion_detection\\ravdes\\'
file = 'C:\\Users\\UPES\\Pictures\\Audio_Speech_analysis\\codes\\firstaudio.wav'
data, sr = sf.read(file, dtype ='float32')
sd.play(data, sr)
status = sd.wait()

In [6]:
emotions = {
    '01':'neutral',
    '02':'calm',
    '03':'happy',
    '04':'sad',
    '05':'angry',
    '06':'fearful',
    '07':'disgust',
    '08':'surprised'  
}

In [7]:
DATADIR = 'C:\\Users\\UPES\\Pictures\\Audio_Speech_analysis\\codes\\pd_data_for_emotion_detection\\ravdes\\'
folders = os.listdir(DATADIR)
count = 0
training_data = [] #load data
for folder in folders:
    path = os.path.join(DATADIR,folder)
    for f in os.listdir(path):
        if f.endswith('.wav'):
            training_data.append(f)
    #count = count+record
#print("Number of recordings ",count)

In [8]:
items = os.listdir(DATADIR)
feeling_list2 = []
for item in items:
    path = os.listdir(DATADIR+item)
    for file in path:
        #0 == female and 1 = male
        #01 = neutral
        #02 = calm
        #03 = happy
        #04 = sad
        #05 = angry
        #06 = fearful
        #07 = disgust
        #08 = surprised
        
        if file[6:-16] =='01': 
             feeling_list2.append('neutral')
        elif file[6:-16] =='02': 
             feeling_list2.append('calm')
        elif file[6:-16] =='03': 
             feeling_list2.append('happy')
        elif file[6:-16] =='04': 
             feeling_list2.append('sad')
        elif file[6:-16] =='05': 
             feeling_list2.append('angry')
        elif file[6:-16] =='06': 
             feeling_list2.append('fearful')
        elif file[6:-16] =='07': 
             feeling_list2.append('disgust')
        elif file[6:-16] =='08': 
             feeling_list2.append('surprised')        
            

In [9]:
len(feeling_list2)

1440

In [10]:
feeling_list2[:20]

['neutral',
 'neutral',
 'neutral',
 'neutral',
 'calm',
 'calm',
 'calm',
 'calm',
 'calm',
 'calm',
 'calm',
 'calm',
 'happy',
 'happy',
 'happy',
 'happy',
 'happy',
 'happy',
 'happy',
 'happy']

In [11]:
x = []
def extract_features(file_path, mfcc, chroma, mel):
    data, s_r = librosa.load(file_path)
    if(chroma):
        stft = np.abs(librosa.stft(data))
    result = np.array([])
    if(mfcc):
        mfccs = np.mean(librosa.feature.mfcc(y = data, sr= s_r, n_mfcc =40).T, axis = 0)
        result = np.hstack((result,mfccs))
    #print(result)
    if(chroma):
        chroma = np.mean(librosa.feature.chroma_stft(S = stft,sr = s_r).T, axis = 0)
        result = np.hstack((result, chroma))
    try:
        if(mel):
            mel = np.mean(librosa.feature.melspectrogram(data,sr = s_r).T, axis = 0)
            result = np.hstack((result, mel))
            x.append(result)
            #print("Done")
    except:
        print("Error")


In [12]:
DATADIR = 'C:\\Users\\UPES\\Pictures\\Audio_Speech_analysis\\codes\\pd_data_for_emotion_detection\\ravdes\\'
folders = os.listdir(DATADIR)
for folder in folders:
    path = os.path.join(DATADIR,folder)
    for f in os.listdir(path):
        if f.endswith('.wav'):
            try:
                file_path = os.path.join(path,f)
                    #print(file_path)
                extract_features(file_path,mfcc = 1, chroma = 1, mel = 1)
            except:
                print("Error")
                break

In [13]:
print(len(x))
print("------------")
print(x[:10])

1440
------------
[array([-6.97984558e+02,  5.52284966e+01,  3.23863178e-01,  1.27753782e+01,
        7.39614630e+00,  8.66223693e-01, -3.55027533e+00, -2.82833123e+00,
       -1.13055353e+01, -2.52492690e+00,  4.96104360e-01, -2.72292614e+00,
        1.64580023e+00, -3.43196464e+00,  1.40356556e-01,  1.07315958e+00,
       -4.35567284e+00, -1.58377111e+00, -1.59300864e+00, -6.59360766e-01,
       -6.20073175e+00, -2.60331273e-01, -2.57398105e+00, -4.29534817e+00,
       -1.89793146e+00, -6.09854817e-01, -5.05881596e+00,  4.46144134e-01,
       -2.32973862e+00,  3.16532463e-01, -2.19781280e+00, -1.96706343e+00,
       -2.85539031e+00, -1.70342696e+00, -3.32837415e+00, -1.43148732e+00,
       -1.19548416e+00, -1.67480683e+00, -3.58714795e+00, -1.46100724e+00,
        7.50463605e-01,  7.89710760e-01,  7.77893186e-01,  7.82118499e-01,
        7.39671528e-01,  6.80501044e-01,  6.83998823e-01,  7.28766799e-01,
        7.55842924e-01,  7.46300340e-01,  7.44283199e-01,  7.22983420e-01,
      

In [14]:
x_train,x_test, y_train, y_test = train_test_split(np.array(x), feeling_list2,test_size = 0.2)
print("Split done!")

Split done!


In [15]:
#Label encode y_train and y_test
lb = LabelEncoder()
#y_train = np_utils.to_categorical(lb.fit_transform(y_train))
#y_test = np_utils.to_categorical(lb.fit_transform(y_test))
print(x_train.shape)
#print(y_train.shape)

(1152, 180)


In [16]:
from sklearn.neural_network import MLPClassifier
clf1 = MLPClassifier(alpha = 0.01,batch_size = 256,epsilon = 1e-08,
                   hidden_layer_sizes = (300,), learning_rate = 'adaptive', max_iter = 500)
#train model
clf1.fit(x_train, y_train)
#predict on test data
y_pred = clf1.predict(x_test)
# Accuracy score
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_true = y_test,y_pred = y_pred)
print(acc*100)

52.43055555555556


In [17]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print("\n")
print(classification_report(y_test,y_pred))

[[26  1  9  1  2  0  0  2]
 [ 1 18  5  1  0  7  5  0]
 [ 2  1 28  0  4  0  3  3]
 [ 1  0  3 22  1  0  6  0]
 [ 5  0  7  7 20  0  5  5]
 [ 1  1  5  0  0  4  6  1]
 [ 3  4  3  2  1  2 14  1]
 [ 1  0 12  0  3  2  2 19]]


              precision    recall  f1-score   support

       angry       0.65      0.63      0.64        41
        calm       0.72      0.49      0.58        37
     disgust       0.39      0.68      0.50        41
     fearful       0.67      0.67      0.67        33
       happy       0.65      0.41      0.50        49
     neutral       0.27      0.22      0.24        18
         sad       0.34      0.47      0.39        30
   surprised       0.61      0.49      0.54        39

   micro avg       0.52      0.52      0.52       288
   macro avg       0.54      0.51      0.51       288
weighted avg       0.56      0.52      0.53       288

